# Generated by Django 3.2.10 on 2024-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailor', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
    ]
