# Generated by Django 3.2.10 on 2024-02-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('length', models.CharField(max_length=15)),
                ('shoulder', models.CharField(max_length=15)),
                ('sleeve_type', models.CharField(choices=[('half_sleeve', 'Half Sleeve'), ('full_sleeve', 'Full Sleeve')], default='half_sleeve', max_length=15)),
                ('sleeve_length', models.CharField(max_length=15)),
                ('neck', models.CharField(max_length=15)),
                ('regal', models.CharField(max_length=15)),
                ('loose', models.CharField(max_length=15)),
                ('pocket', models.CharField(max_length=15)),
                ('cuff_type', models.CharField(choices=[('cuff', 'Cuff'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('cuff_length', models.CharField(max_length=15)),
                ('bottom1', models.CharField(max_length=50)),
                ('bottom2', models.CharField(max_length=50)),
                ('button_type', models.CharField(choices=[('bayyin_mahfi', 'Bayyin Mahfi'), ('zip_mahfi', 'Zip Mahfi'), ('button_bayyin', 'Button Bayyin')], max_length=15)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('tailor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.addtailor')),
            ],
        ),
    ]
