# Generated by Django 3.2.10 on 2024-02-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddTailor',
            new_name='AddTailors',
        ),
    ]
