# Generated by Django 5.0.1 on 2024-02-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_customer_collar_customer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtailors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
