# Generated by Django 5.0.1 on 2024-02-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_order_delete_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
