# Generated by Django 5.0.1 on 2024-02-24 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_addtailors_options_alter_addtailors_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtailors',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
