# Generated by Django 5.0.1 on 2024-02-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_addtailors_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtailors',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
