# Generated by Django 5.0.1 on 2024-02-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_addtailors_password_alter_addtailors_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtailors',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='addtailors',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
