# Generated by Django 5.0.1 on 2024-02-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtailors',
            name='assigned_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addtailors',
            name='completed_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addtailors',
            name='pending_works',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addtailors',
            name='upcoming_works',
            field=models.IntegerField(default=0),
        ),
    ]
