# Generated by Django 3.2.10 on 2024-02-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_addtailors_assigned_works_addtailors_completed_works_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtailors',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
