# Generated by Django 3.2.10 on 2024-03-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_admin_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_login',
            old_name='user_name',
            new_name='username',
        ),
    ]
