# Generated by Django 3.2.10 on 2024-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_rename_user_name_admin_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cloth',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
