# Generated by Django 3.2.10 on 2024-03-04 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_customer_cloth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15)),
                ('length', models.CharField(max_length=15)),
                ('shoulder', models.CharField(max_length=15)),
                ('cloth', models.CharField(max_length=20, null=True)),
                ('sleeve_type', models.CharField(choices=[('half_sleeve', 'Half Sleeve'), ('full_sleeve', 'Full Sleeve')], default='half_sleeve', max_length=15)),
                ('sleeve_length', models.CharField(max_length=15)),
                ('neck', models.CharField(max_length=15)),
                ('neck_round', models.CharField(max_length=15, null=True)),
                ('collar', models.CharField(max_length=15, null=True)),
                ('regal', models.CharField(max_length=15)),
                ('loose', models.CharField(max_length=15)),
                ('wrist', models.CharField(max_length=15, null=True)),
                ('pocket', models.CharField(max_length=15)),
                ('cuff_type', models.CharField(choices=[('cuff', 'Cuff'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('cuff_length', models.CharField(max_length=15)),
                ('bottom1', models.CharField(max_length=50)),
                ('bottom2', models.CharField(max_length=50)),
                ('button_type', models.CharField(choices=[('bayyin_mahfi', 'Bayyin Mahfi'), ('zip_mahfi', 'Zip Mahfi'), ('mahfi', 'Mahfi'), ('button_bayyin', 'Button Bayyin')], max_length=15)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=100000, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('bill_number', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('tailor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
