# Generated by Django 3.2.10 on 2024-03-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_add_order_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_order',
            old_name='name',
            new_name='customer_id',
        ),
        migrations.RemoveField(
            model_name='add_order',
            name='mobile',
        ),
    ]
