# Generated by Django 3.2.10 on 2024-03-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20240305_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_order',
            name='bottom1',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='bottom2',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='collar',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='cuff_length',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='length',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='loose',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='neck',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='neck_round',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='pocket',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='regal',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='shoulder',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='sleeve_length',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='wrist',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bottom1',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bottom2',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='collar',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cuff_length',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='length',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loose',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='neck',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='neck_round',
            field=models.FloatField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pocket',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regal',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shoulder',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sleeve_length',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wrist',
            field=models.FloatField(max_length=15, null=True),
        ),
    ]
