# Generated by Django 3.2.10 on 2024-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20240309_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_order',
            name='button_type',
            field=models.CharField(choices=[('makfi', 'Makfi'), ('makfi_bayyin', 'Makfi Bayyin'), ('button_bayyin', 'Button Bayyin'), ('makfi_op', 'Makfi OP'), ('makfi_op_nice', 'Makfi OP Nice'), ('makfi_nice', 'Makfi Nice'), ('makfi_zip', 'Makfi Zip'), ('dabble_zib', 'Dabble Zib')], max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='sleeve_type',
            field=models.CharField(choices=[('sada_sleeve', 'Sada Sleeve'), ('cuff_sleeve', 'Cuff Sleeve'), ('center_sleeve', 'Center Sleeve')], default='half_sleeve', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='button_type',
            field=models.CharField(choices=[('makfi', 'Makfi'), ('makfi_bayyin', 'Makfi Bayyin'), ('button_bayyin', 'Button Bayyin'), ('makfi_op', 'Makfi OP'), ('makfi_op_nice', 'Makfi OP Nice'), ('makfi_nice', 'Makfi Nice'), ('makfi_zip', 'Makfi Zip'), ('dabble_zib', 'Dabble Zib')], max_length=15),
        ),
    ]
