# Generated by Django 3.2.10 on 2024-03-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20240311_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_order',
            old_name='cuff_size',
            new_name='cuff_length',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cuff_size',
            new_name='cuff_length',
        ),
    ]
