# Generated by Django 3.2.10 on 2024-03-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20240311_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='collar_size',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='add_order',
            name='sleeve_bottom',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='collar_size',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sleeve_bottom',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='bottom1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='collar',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='cuff_length',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='length',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='loose',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='neck',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='pocket',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='regal',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='seat',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='shoulder',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='sleeve_cuff',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='add_order',
            name='sleeve_sada',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bottom1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='collar',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cuff_length',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='length',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loose',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='neck',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pocket',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='regal',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='seat',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shoulder',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sleeve_cuff',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sleeve_sada',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
