# Generated by Django 3.2.10 on 2024-03-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20240312_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='advance_payment',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='add_order',
            name='balance_payment',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='add_order',
            name='total_payment',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
