# Generated by Django 3.2.10 on 2024-03-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20240323_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='pending_or_delivered',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
