# Generated by Django 3.2.10 on 2024-04-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20240409_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_order',
            name='neck',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='neck',
        ),
        migrations.AddField(
            model_name='add_order',
            name='center_sleeve',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='center_sleeve',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
