# Generated by Django 3.2.10 on 2024-04-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20240409_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='model_details',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='model_details',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
