# Generated by Django 3.2.10 on 2024-04-24 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20240413_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_login',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='username',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='user_name',
        ),
        migrations.AddField(
            model_name='admin_login',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reception_login',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reception', to=settings.AUTH_USER_MODEL),
        ),
    ]
