# Generated by Django 3.2.10 on 2024-04-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20240424_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_order',
            name='tailor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.addtailors'),
        ),
        migrations.AlterField(
            model_name='admin_login',
            name='username',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
