# Generated by Django 3.2.10 on 2024-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0044_auto_20240424_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtailors',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='admin_login',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reception_login',
            options={},
        ),
        migrations.AlterModelManagers(
            name='admin_login',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='reception_login',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='admin_login',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='reception_login',
            name='username',
        ),
        migrations.AddField(
            model_name='addtailors',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='addtailors',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='reception_login',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admin_login',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admin_login',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reception_login',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
