# Generated by Django 3.2.10 on 2024-05-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20240510_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='pocket_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pocket_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
