# Generated by Django 3.2.10 on 2024-06-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20240511_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
