# Generated by Django 3.2.10 on 2024-06-07 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_add_order_is_printed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_order',
            name='clothdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cloth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='clothdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cloth'),
        ),
    ]
