# Generated by Django 3.2.10 on 2024-06-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20240607_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_order',
            name='cloth_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cloth_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
