# Generated by Django 3.2.10 on 2024-06-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20240607_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_order',
            name='cloth_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cloth_name',
        ),
        migrations.AlterField(
            model_name='add_order',
            name='clothdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cloth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='clothdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cloth'),
        ),
    ]
