# Generated by Django 5.0.1 on 2024-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0003_tailor_order_tailor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='hips',
            new_name='arm',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='inseam',
            new_name='neck',
        ),
        migrations.AddField(
            model_name='measurement',
            name='shoulder',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='measurement',
            name='wrist',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
