# Generated by Django 5.0.1 on 2024-02-17 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0006_addcustomer_delete_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailors.addcustomer'),
        ),
        migrations.RemoveField(
            model_name='addcustomer',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
