# Generated by Django 5.0.1 on 2024-02-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0007_alter_order_customer_remove_addcustomer_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
