# Generated by Django 5.0.1 on 2024-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0013_alter_addcustomer_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='bill_number',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
