# Generated by Django 5.0.1 on 2024-02-17 09:15

import tailors.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0015_alter_addcustomer_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='AddCustomer',
            name='bill_number',
            field=models.CharField(default=tailors.utils.generate_bill_number, editable=False, max_length=50, unique=True),
        ),
    ]
