# Generated by Django 5.0.1 on 2024-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0017_alter_addcustomer_cuf_alter_addcustomer_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
