# Generated by Django 5.0.1 on 2024-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0018_tailor_password_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
