# Generated by Django 5.0.1 on 2024-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0019_alter_tailor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailor',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
