# Generated by Django 5.0.1 on 2024-02-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0023_alter_addcustomer_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailor_name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='bill_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailors.addtailor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailors.addtailor'),
        ),
        migrations.DeleteModel(
            name='Tailor',
        ),
    ]
