# Generated by Django 5.0.1 on 2024-02-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0024_addtailor_alter_addcustomer_bill_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailors.addcustomer')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailors.addtailor')),
            ],
        ),
    ]
