# Generated by Django 5.0.1 on 2024-02-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0025_workstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtailor',
            name='mobile_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
