# Generated by Django 5.0.1 on 2024-02-19 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0026_alter_addtailor_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomer',
            name='bottom1',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='bottom2',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='button_type',
            field=models.CharField(blank=True, choices=[('bayyin_mahfi', 'Bayyin Mahfi'), ('zip_mahfi', 'Zip Mahfi'), ('button_bayyin', 'Button Bayyin')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='sleeve_type',
            field=models.CharField(choices=[('half_sleeve', 'Half Sleeve'), ('full_sleeve', 'Full Sleeve')], default='half_sleeve', max_length=15),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='phone_number',
            field=models.CharField(default='1', max_length=15),
        ),
    ]
