# Generated by Django 5.0.1 on 2024-02-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0027_addcustomer_bottom1_addcustomer_bottom2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomer',
            name='cuftype',
            field=models.CharField(choices=[('cuff', 'Cuff'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='cuf',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
