# Generated by Django 3.2.10 on 2024-02-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0031_rename_tailor_name_addtailor_tailor'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomer',
            name='pocket_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
